version: "3.9"
services:
  server:
    build: .
    ports:
      - "8088:5000"
    env_file:
      - .env
    links:
      - redis
      - mysql
  mysql:
    image: mysql:8
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

    # volumes:
    #   - ~/apps/mysql:/var/lib/mysql
  redis:
    image: "redis:alpine"