"""empty message

Revision ID: 18b219ea604a
Revises: 7acb3fb2f2d1
Create Date: 2022-04-27 10:06:12.059336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18b219ea604a'
down_revision = '7acb3fb2f2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched', sa.Column('backdrop_path', sa.Text(), nullable=True))
    op.add_column('watched', sa.Column('media_type', sa.String(length=32), nullable=True))
    op.add_column('watched', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'watched', 'user', ['user_id'], ['id'])
    op.drop_column('watched', 'meida_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched', sa.Column('meida_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True))
    op.drop_constraint(None, 'watched', type_='foreignkey')
    op.drop_column('watched', 'user_id')
    op.drop_column('watched', 'media_type')
    op.drop_column('watched', 'backdrop_path')
    # ### end Alembic commands ###
