"""empty message

Revision ID: 253140eabc4b
Revises: bb54c5aeecf4
Create Date: 2022-05-30 14:09:54.586933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253140eabc4b'
down_revision = 'bb54c5aeecf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('num_projects', sa.Integer(), nullable=True),
    sa.Column('work_experience', sa.Integer(), nullable=True),
    sa.Column('educational_background', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_information')
    # ### end Alembic commands ###
