"""empty message

Revision ID: 2e5898520366
Revises: 5f81b2a69fed
Create Date: 2022-04-15 16:29:46.185516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5898520366'
down_revision = '5f81b2a69fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_mini_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('app_secret', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat_mini_program')
    # ### end Alembic commands ###
