"""add_work_history_table

Revision ID: 3b283bfd6a1d
Revises: d6f33cc1c6cf
Create Date: 2022-06-03 13:33:10.819520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b283bfd6a1d'
down_revision = 'd6f33cc1c6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('time_period', sa.String(length=128), nullable=False),
    sa.Column('jobs', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('personal_information_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personal_information_id'], ['personal_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_history')
    # ### end Alembic commands ###
