"""empty message

Revision ID: 4fc496bedbb3
Revises: 18b219ea604a
Create Date: 2022-04-27 16:46:28.646975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc496bedbb3'
down_revision = '18b219ea604a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('want_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('tmdb_id', sa.String(length=255), nullable=False),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('backdrop_path', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('want_watch')
    # ### end Alembic commands ###
