"""empty message

Revision ID: 70c235e21b3f
Revises: 58f8575d122b
Create Date: 2022-04-22 17:03:47.514348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70c235e21b3f'
down_revision = '58f8575d122b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wechat_user', 'mobile',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wechat_user', 'mobile',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               nullable=False)
    # ### end Alembic commands ###
