"""empty message

Revision ID: 7acb3fb2f2d1
Revises: 70c235e21b3f
Create Date: 2022-04-26 16:27:48.416211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acb3fb2f2d1'
down_revision = '70c235e21b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('meida_type', sa.String(length=32), nullable=True),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched')
    # ### end Alembic commands ###
