"""add_other_info_column_to_personal_information

Revision ID: 7bc8553da344
Revises: a8d62125ecf0
Create Date: 2022-06-03 17:46:25.025865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc8553da344'
down_revision = 'a8d62125ecf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_information', sa.Column('other_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_information', 'other_info')
    # ### end Alembic commands ###
