"""empty message

Revision ID: a33de1c2cb42
Revises: a6f6da3fc271
Create Date: 2022-04-19 15:25:25.738362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33de1c2cb42'
down_revision = 'a6f6da3fc271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('wechat_userid', sa.String(length=255), nullable=True),
    sa.Column('wechat_openid', sa.String(length=255), nullable=True),
    sa.Column('wechat_unionid', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat_user')
    # ### end Alembic commands ###
