"""empty message

Revision ID: bb54c5aeecf4
Revises: 2333bf51191e
Create Date: 2022-05-16 16:32:54.472345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb54c5aeecf4'
down_revision = '2333bf51191e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_mini_program', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('wechat_mini_program', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_mini_program', 'updated_at')
    op.drop_column('wechat_mini_program', 'created_at')
    # ### end Alembic commands ###
