"""empty message

Revision ID: d6f33cc1c6cf
Revises: 253140eabc4b
Create Date: 2022-06-01 22:59:34.097940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f33cc1c6cf'
down_revision = '253140eabc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_information', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_information', 'birthday')
    # ### end Alembic commands ###
